
apiVersion: v1
kind: Namespace
metadata:
  name: amir-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amir-sa
  namespace: amir-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amir-config
  namespace: amir-ns
data:
  APP_NAME: amir
  APP_ENV: production
---
apiVersion: v1
kind: Secret
metadata:
  name: amir-secret
  namespace: amir-ns
type: Opaque
stringData:
  APP_SECRET: change-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amir
  namespace: amir-ns
spec:
  replicas: 6
  selector:
    matchLabels:
      app: amir
  template:
    metadata:
      labels:
        app: amir
    spec:
      serviceAccountName: amir-sa
      containers:
        - name: amir
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: amir-config
            - secretRef:
                name: amir-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: amir-svc
  namespace: amir-ns
spec:
  selector:
    app: amir
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amir-allow-svc-port
  namespace: amir-ns
spec:
  podSelector:
    matchLabels:
      app: amir
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amir-hpa
  namespace: amir-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amir
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amir-ing
  namespace: amir-ns
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.amirodevops.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amir-svc
                port:
                  number: 80
